@extends('layouts.app')

@section('title', 'Gestion des utilisateurs | OEV')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
  <div class="page-heading">
    <div class="page-heading-copy"><span class="page-icon"><i class="bi bi-people" aria-hidden="true"></i></span><div><p class="eyebrow mb-1">Administration</p><h1 class="h3 mb-1">Gestion des utilisateurs</h1><p class="text-muted mb-0">{{ $users->total() }} compte(s) trouvé(s).</p></div></div>
    <button class="btn btn-primary btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#ajouterUtilisateurModal" aria-label="Ajouter un utilisateur" title="Ajouter un utilisateur"><i class="fa-solid fa-user-plus" aria-hidden="true"></i></button>
  </div>

  @if (session('success')) <div class="alert alert-success mt-3">{{ session('success') }}</div> @endif
  @if ($errors->any()) <div class="alert alert-danger mt-3">{{ $errors->first() }}</div> @endif

  <section class="panel mt-3">
    <div class="panel-header"><div><h2 class="h5 mb-1">Utilisateurs enregistrés</h2><p class="text-muted mb-0">Les comptes sont chargés depuis la base de données.</p></div><input class="form-control form-control-sm table-search" type="search" placeholder="Rechercher dans la page" data-table-search="usersTable" aria-label="Rechercher un utilisateur"></div>
    <div class="table-responsive"><table class="table align-middle mb-0" id="usersTable" data-searchable-table><thead><tr><th>Utilisateur</th><th>Rôle(s)</th><th>Statut</th><th>Créé le</th><th class="text-end">Actions</th></tr></thead><tbody>
      @forelse ($users as $user)
        <tr><td><strong>{{ $user->name }}</strong><br><small class="text-muted">{{ $user->email }}</small></td><td>{{ $user->roles->pluck('name')->join(', ') ?: 'Aucun rôle' }}</td><td><span class="badge text-bg-{{ $user->active ? 'success' : 'secondary' }}">{{ $user->active ? 'Actif' : 'Désactivé' }}</span></td><td>{{ $user->created_at?->format('d/m/Y') }}</td><td class="text-end"><div class="btn-group btn-group-sm"><button class="btn btn-light" type="button" data-bs-toggle="modal" data-bs-target="#detailsUtilisateur{{ $user->id }}" aria-label="Voir l’utilisateur" title="Voir"><i class="fa-solid fa-eye" aria-hidden="true"></i></button><button class="btn btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#modifierUtilisateur{{ $user->id }}" aria-label="Modifier l’utilisateur" title="Modifier"><i class="fa-solid fa-pen-to-square" aria-hidden="true"></i></button><form method="POST" action="{{ route('users.destroy', $user) }}" onsubmit="return confirm('Supprimer cet utilisateur ?');">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit" aria-label="Supprimer l’utilisateur" title="Supprimer"><i class="fa-solid fa-trash" aria-hidden="true"></i></button></form></div></td></tr>
      @empty
        <tr><td colspan="5" class="text-center text-muted py-4">Aucun utilisateur enregistré.</td></tr>
      @endforelse
    </tbody></table></div>
    <div class="d-flex justify-content-end mt-3">{{ $users->links() }}</div>
  </section>
</div>

<div class="modal fade" id="ajouterUtilisateurModal" tabindex="-1" aria-labelledby="ajouterUtilisateurModalLabel" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5" id="ajouterUtilisateurModalLabel">Ajouter un utilisateur</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button></div><form method="POST" action="{{ route('users.store') }}">@csrf<div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="modal-name">Nom complet</label><input class="form-control" id="modal-name" name="name" value="{{ old('name') }}" required></div><div class="col-md-6"><label class="form-label" for="modal-email">Adresse e-mail</label><input class="form-control" id="modal-email" name="email" type="email" value="{{ old('email') }}" required></div><div class="col-md-6"><label class="form-label" for="modal-password">Mot de passe</label><input class="form-control" id="modal-password" name="password" type="password" required></div><div class="col-md-6"><label class="form-label" for="modal-password-confirmation">Confirmation</label><input class="form-control" id="modal-password-confirmation" name="password_confirmation" type="password" required></div><div class="col-12"><label class="form-label" for="modal-role">Rôle</label><select class="form-select" id="modal-role" name="role" required><option value="">Sélectionner un rôle</option>@foreach ($roles as $role)<option value="{{ $role->name }}">{{ $role->name }}</option>@endforeach</select></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Annuler</button><button class="btn btn-primary" type="submit">Créer l’utilisateur</button></div></form></div></div></div>

@foreach ($users as $user)
<div class="modal fade" id="detailsUtilisateur{{ $user->id }}" tabindex="-1" aria-labelledby="detailsUtilisateurLabel{{ $user->id }}" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5" id="detailsUtilisateurLabel{{ $user->id }}">Détails de l’utilisateur</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button></div><div class="modal-body"><dl class="row mb-0"><dt class="col-sm-4">Nom</dt><dd class="col-sm-8">{{ $user->name }}</dd><dt class="col-sm-4">E-mail</dt><dd class="col-sm-8">{{ $user->email }}</dd><dt class="col-sm-4">Rôle(s)</dt><dd class="col-sm-8">{{ $user->roles->pluck('name')->join(', ') ?: 'Aucun rôle' }}</dd><dt class="col-sm-4">Créé le</dt><dd class="col-sm-8">{{ $user->created_at?->format('d/m/Y') }}</dd></dl></div></div></div></div>
<div class="modal fade" id="modifierUtilisateur{{ $user->id }}" tabindex="-1" aria-labelledby="modifierUtilisateurLabel{{ $user->id }}" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5" id="modifierUtilisateurLabel{{ $user->id }}">Modifier l’utilisateur</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button></div><form method="POST" action="{{ route('users.update', $user) }}">@csrf @method('PUT')<div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="nom-{{ $user->id }}">Nom complet</label><input class="form-control" id="nom-{{ $user->id }}" name="name" value="{{ $user->name }}" required></div><div class="col-md-6"><label class="form-label" for="email-{{ $user->id }}">Adresse e-mail</label><input class="form-control" id="email-{{ $user->id }}" name="email" type="email" value="{{ $user->email }}" required></div><div class="col-12"><label class="form-label" for="role-{{ $user->id }}">Rôle</label><select class="form-select" id="role-{{ $user->id }}" name="role"><option value="">Conserver le rôle actuel</option>@foreach ($roles as $role)<option value="{{ $role->name }}" @selected($user->roles->contains('name', $role->name))>{{ $role->name }}</option>@endforeach</select></div><div class="col-12"><div class="form-check form-switch"><input type="hidden" name="active" value="0"><input class="form-check-input" id="active-{{ $user->id }}" name="active" value="1" type="checkbox" @checked($user->active)><label class="form-check-label" for="active-{{ $user->id }}">Compte actif et autorisé à se connecter</label></div></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Annuler</button><button class="btn btn-primary" type="submit">Enregistrer</button></div></form></div></div></div>
@endforeach
@endsection
